version: '3'
services:
  db1:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql



  rabbitmq:
    image: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
    ports:
      - "5672:5672"



  app-film:
    container_name: film
    build:
      context: ./FilmMicroservice/
    restart: always
    depends_on:
      - db1
      - rabbitmq
    env_file:
      - .environment.env
    ports:
      - "5000:5000"


  listener-persons:
    build: ./PersonsMicroService/
    depends_on:
      - db1
      - rabbitmq
    env_file:
      - .environment.env
    command: npm run PersonsListenerDD


  app-person:
    container_name: person
    build:
      context: ./PersonsMicroService/
    restart: always
    depends_on:
      - db1
      - rabbitmq

    env_file:
      - .environment.env
    ports:
      - "5100:5100"

  app-auth:
    container_name: auth
    build:
      context: ./AuthMicroservice/
    restart: always
    depends_on:
      - db1
      - rabbitmq

    env_file:
      - .environment.env
    ports:
      - "5010:5010"

  comments:
    container_name: comments
    build:
      context: ./commentsMicroService/
    restart: always
    env_file:
      - .environment.env
    volumes:
      - .:/app
      - /app
    ports:
      - "8000:8000"
    depends_on:
      - db1

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecretPassword